# Generated by Django 4.0 on 2022-01-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_alter_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='short_cut',
            new_name='city_code',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='short_cut',
            new_name='city_code',
        ),
    ]
