# Generated by Django 4.0 on 2021-12-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hotel_manger',
            new_name='is_hotel_manager',
        ),
    ]
